language: python
install: true
script: true
deploy:
  provider: cloudfoundry
  username: msoliter@gmail.com
  password: $DEPLOYMENT_KEY
  api: https://api.run.pivotal.io
  organization: msoliter
  space: cowbot
env:
  global:
    secure: Qb9JjYvmgeLnnOrqX0wWoVKnUmOidqPofXRawjwtDeZkWIolyT3v5rOj2oBwZlH3DEqLAESS2Ljk47RviDaI0G9N8yffCguLUhIDBtzA5Vq96jfKYvsrcW9eHesoEHZDwyp2RX3uykmCGbyyoFADFrIdqzCEGN8QVYpRvlJFQbo=
